# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = shm_db_sync

BASE_DIRECTORY = ..

TARGET_SRCS = shm_db_sync.c

TARGET_INCLUDES = 

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
