/* FILE GENERATO AUTOMATICAMENTE A PARTIRE DA asmop.lst */

const char *asmop_list[] = {
/* AOP_COMMENT */ "%b/%1%c",
/* AOP_TMPID */ "%b.L%1%c",
/* AOP_STRID */ "%b.LS%1%c",
/* AOP_SYMPLOFF */ "%b%1+%2%c",
/* AOP_FIRSTLABEL */ "%bilc.compiled:",
/* AOP_LALIGN */ ".align 4",
/* AOP_DATA */ ".data",
/* AOP_TEXT */ ".text",
/* AOP_BYTE */ ".byte %c",
/* AOP_SHORT */ ".short %c",
/* AOP_LONG */ ".long %c",
/* AOP_SPACE */ ".space %1,%2",
/* AOP_ASCIZ */ ".asciz \"%1\"",
/* AOP_LABEL */ "%b%1:",
/* AOP_EXTERN */ ".extern %1",
/* AOP_GLOBAL */ ".globl %1",
/* AOP_NOP */ "nop",
/* AOP_RET */ "ret",
/* AOP_CLTD */ "cltd",
/* AOP_MOVL */ "movl %1,%2",
/* AOP_MOVB */ "movb %1,%2",
/* AOP_MOVW */ "movw %1,%2",
/* AOP_MOVSBL */ "movsbl %1,%2",
/* AOP_MOVSWL */ "movswl %1,%2",
/* AOP_MOVZBL */ "movzbl %1,%2",
/* AOP_MOVZWL */ "movzwl %1,%2",
/* AOP_PUSHL */ "pushl %1",
/* AOP_POPL */ "popl %1",
/* AOP_CALL */ "call %1",
/* AOP_JMP */ "jmp %1",
/* AOP_JE */ "je %1",
/* AOP_JNE */ "jne %1",
/* AOP_TESTL */ "testl %1,%2",
/* AOP_SETE */ "sete %1",
/* AOP_SETNE */ "setne %1",
/* AOP_SETA */ "seta %1",
/* AOP_SETAE */ "setae %1",
/* AOP_SETB */ "setb %1",
/* AOP_SETBE */ "setbe %1",
/* AOP_SETG */ "setg %1",
/* AOP_SETGE */ "setge %1",
/* AOP_SETL */ "setl %1",
/* AOP_SETLE */ "setle %1",
/* AOP_NOTL */ "notl %1",
/* AOP_ANDB */ "andb %1,%2",
/* AOP_ANDW */ "andw %1,%2",
/* AOP_ANDL */ "andl %1,%2",
/* AOP_XORB */ "xorb %1,%2",
/* AOP_XORW */ "xorw %1,%2",
/* AOP_XORL */ "xorl %1,%2",
/* AOP_ORB */ "orb %1,%2",
/* AOP_ORW */ "orw %1,%2",
/* AOP_ORL */ "orl %1,%2",
/* AOP_ADDB */ "addb %1,%2",
/* AOP_ADDW */ "addw %1,%2",
/* AOP_ADDL */ "addl %1,%2",
/* AOP_SUBB */ "subb %1,%2",
/* AOP_SUBW */ "subw %1,%2",
/* AOP_SUBL */ "subl %1,%2",
/* AOP_CMPB */ "cmpb %1,%2",
/* AOP_CMPW */ "cmpw %1,%2",
/* AOP_CMPL */ "cmpl %1,%2",
/* AOP_IMULB */ "imulb %1,%2",
/* AOP_IMULW */ "imulw %1,%2",
/* AOP_IMULL */ "imull %1,%2",
/* AOP_LEAL */ "leal %1,%2",
/* AOP_XCHGL */ "xchgl %1,%2",
/* AOP_INCL */ "incl %1",
/* AOP_DECL */ "decl %1",
/* AOP_EIDIVL */ "idivl %1,%2",
/* AOP_EDIVL */ "divl %1,%2",
/* AOP_SWAP16 */ "rol $0x10,%1",
/* AOP_ERRBOUND */ "jae _il_rtmerr_subscript",
/* AOP_ERRBOUND2 */ "jb .+7\n call _il_ex_rtmerr_subscript",
/* AOP_FILE */ ".file \"%1\"",
/* AOP_DIRINFO */ "%b.stabs \"%1\",100,0,0,ilc.compiled",
/* AOP_FILEINFO */ "%b.stabs \"%1\",100,0,0,ilc.compiled",
/* AOP_LINEINFO */ "%b.stabn 68,0,%1,.LM%3-%2\n.LM%3:",
/* AOP_TYPEINFO */ "%b.stabs \"int:t1=r1;-2147483648;2147483647;\",128,0,0,0",
/* AOP_FUNCINFO */ "%b.stabs \"%1:F1\",36,0,%2,%1",
/* AOP_FILEINFO2 */ "%b$BF%1:",
/* AOP_EFILEINFO2 */ "%b$EF%1:",
/* AOP_LINEINFO2 */ "%b$LN%1$%3:",
/* AOP_ELINEINFO2 */ "%b$LE%1$%3:",
/* AOP_FUNCINFO2 */ "%b$FN%1 = %2",
/* AOP_VALINFO2 */ "%b$VA%1$%2$%3$%4 = %5",
/* AOP_INDINFO2 */ "%b$VI%1$%2$%3:",
/* AOP_JMPINFO2 */ "%b$LJ%1$%2:",
/* AOP_LBLINFO2 */ "%b$LL%1$%2:",
};
