/* FILE GENERATO AUTOMATICAMENTE A PARTIRE DA errlist.lst */

const char *err_list[] = {
/* PA_E_OK */ "OK",
/* PA_E_NCP */ "Missing ')'",
/* PA_E_NOP */ "Missing '('",
/* PA_E_NOSQ */ "Missing '['",
/* PA_E_NCSQ */ "Missing ']'",
/* PA_E_NID */ "Identifier expected",
/* PA_E_NCONST */ "Constant expected",
/* PA_E_NSC */ "Missing ';'",
/* PA_E_NSP */ "Missing ':'",
/* PA_E_NOQU */ "Missing '",
/* PA_E_BADTK */ "Bad token",
/* PA_E_ICH */ "Illegal character or keyword",
/* PA_E_KWU */ "Keyword unexpected",
/* PA_E_INERR */ "Internal error",
/* PA_E_NEND_CONF */ "END_CONFIGURATION expected",
/* PA_E_NEND_RES */ "END_RESOURCE expected",
/* PA_E_NON */ "ON expected",
/* PA_E_NEND_VAR */ "END_VAR or END_TYPE expected",
/* PA_E_NASSOC_I */ "Constant value or direct input expected",
/* PA_E_NASSOC_O */ "Direct output expected",
/* PA_E_NASSOC_IO */ "I/O configuration expected",
/* PA_E_NTYPE */ "Type expected",
/* PA_E_NINIT */ "Initializer expected",
/* PA_E_NOF */ "OF expected",
/* PA_E_NDIMS */ "Subrange expected",
/* PA_E_NDOTS */ "'..' expected",
/* PA_E_NOPR */ "Missing operand",
/* PA_E_NINDEX */ "Index expected",
/* PA_E_NEOL */ "End of line expected",
/* PA_E_NASGN */ "':=' expected",
/* PA_E_NENDPROC */ "END_PROGRAM, END_FUNCTION or END_FUNCTION_BLOCK expected",
/* PA_E_UNSUPP */ "Unsupported function",
/* LA_E_NOMEM */ "No memory",
/* LA_E_DIV0 */ "Division by 0",
/* LA_E_MOD0 */ "MOD by 0",
/* LA_E_NOFILE */ "Can't open file",
/* LA_E_REDEF */ "Symbol redefined :",
/* LA_W_HIDES */ "Local variable hides a global :",
/* LA_E_RETAIN_AT */ "Variables can't have RETAIN and AT attributes simultaneously",
/* LA_E_LOCAL_AT */ "Only global variables can have a direct address",
/* LA_E_LOCAL_RETAIN */ "Only global variables can have RETAIN attribute",
/* LA_E_NONINT_DIM */ "Array index must be integer",
/* LA_E_BADDIM */ "Last subrange value must be greater than first",
/* LA_E_TOODIM */ "Too many dimensions",
/* LA_E_TYPEMIS */ "Type mismatch",
/* LA_W_CONVTOREAL */ "Conversion to floating point format",
/* LA_W_TRUNCINT */ "Integer value out of range",
/* LA_E_ININONUM */ "Only numeric variables can be initialized",
/* LA_E_ININOMEM */ "Only local and global variables can be initialized",
/* LA_E_INIDIRV */ "Cannot initialize direct variables",
/* LA_E_BADCOUNT */ "Bad repetition index",
/* LA_E_TOOMINIT */ "Too many initializers",
/* LA_E_DIFFTYPE */ "Different type declaration in VAR_GLOBAL and VAR_EXTERNAL :",
/* LA_E_NOTATYPE */ "This doesn't seem neither a type nor a function block :",
/* LA_E_NOSCALFN */ "Functions can only return scalar numeric values",
/* LA_E_MODFLOAT */ "MOD of REAL value",
/* LA_E_INIDIRV2 */ "Can only initialize direct outputs",
/* LA_E_NSQB */ "Array initializer expected",
/* LA_E_NOTARRAY */ "Scalar initializer expected",
/* LA_E_NOTYPE */ "Type unknown :",
/* LA_E_UNDEFSYM */ "Symbol undefined :",
/* LA_E_UNTMLILEXPR */ "Unterminated multi-line expression",
/* LA_E_DIFFILLEV */ "Jump to different expression level",
/* LA_E_JMPOOC */ "Cannot jump out of a multi-line expression",
/* LA_E_TOORES */ "Too many resources",
/* LA_E_NOTAPROG */ "This isn't a program :",
/* LA_E_NOTIO */ "This doesn't seem neither an INPUT nor an OUTPUT :",
/* LA_E_DUPASGN */ "Duplicated MSD entry :",
/* LA_W_UNASGN */ "Unassigned parameter :",
/* LA_W_SIZE */ "Variable size mismatch",
/* LA_E_TOOILEXPR */ "Too many nested IL expression",
/* LA_E_NOTAVAR */ "This isn't a variable :",
/* LA_E_NOTAFB */ "This doesn't seem a function block :",
/* LA_E_INCIND */ "Incorrect subscripts number",
/* LA_E_INDOUT */ "Subscript out of range",
/* LA_E_TOOPARAM */ "Too many function parameters",
/* LA_W_UNACC */ "Current value undefined. Assuming 0",
};
