/* QUESTO FILE E` STATO GENERATO IN MODO AUTOMATICO A PARTIRE DA parser_c.h */
/* NON APPORTARE MODIFICHE QUI, MA SOLO IN parser.c */
static void paCallback(int code);
static void paUndef(void);
static int paJunk(void);
static int paILIndex(void);
static int paILIndexList(void);
static int paILLValue(void);
static int paILConstantExpression(void);
static int paILArgument(void);
static int paILExtendedArgument(void);
static int paILLabel(void);
static int paILAssign(void);
static int paILFormalList(void);
static int paILExpr(void);
static int paILStatement(void);
static int paILInstruction(void);
static int paIL(void);
static int paST(void);
static int paString(void);
static int paConstant(void);
static int paPrimary(void);
static int paHeir9(void);
static int paHeir8(void);
static int paHeir7(void);
static int paHeir6(void);
static int paHeir5(void);
static int paHeir4(void);
static int paHeir3(void);
static int paHeir2(void);
static int paHeir1(void);
static int paConstantExpression(void);
static int paInitString(void);
static int paInitConstantExpression(void);
static int paConstantIntegerExpression(void);
static int paInputVarDeclaration(void);
static int paOutputVarDeclaration(void);
static int paLocalVarDeclaration(void);
static int paBody(void);
static int paGenericProcedure(int k_begin,int op_begin,int k_end,int op_end);
static int paProgram(void);
static int paFunction(void);
static int paFunctionBlock(void);
static int paTypeDecl(void);
static int paVarDecl(void);
static int paArrayInitElem(void);
static int paArrayInitList(void);
static int paArrayInit(void);
static int paScalarType(void);
static int paSubrange(void);
static int paArrayType(void);
static int paType(void);
static int paTypeAndInit(void);
static int paVarDeclElement(void);
static int paGenericSymDecl(int k_begin,int op_begin,int k_end,int op_end);
static int paGenericVarDecl(int k_begin,int op_begin,int op_end);
static int paExternalVarDecl(void);
static int paGlobalVarDecl(void);
static int paProgramIOConf(void);
static int paProgramInstance(void);
static int paResource(void);
static int paConfiguration(void);
static int paIEC1131Construct(void);
