# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = balance

BASE_DIRECTORY = ..

TARGET_SRCS = main.c mainapp.c mainwin.c editarticolo.c balance.c mainvar.c mainfun.c mainproc.c resources.c

TARGET_INCLUDES = mainstruct.h mainext.h mainapp.h mainwin.h editarticolo.h mainfun.h balance.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
