# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = auto_tasks

BASE_DIRECTORY = ..

TARGET_SRCS = mainfun.c mainutil.c mainvar.c main.c

TARGET_INCLUDES = main.h mainext.h mainstruct.h mainfun.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
