# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = receive-rcs

BASE_DIRECTORY = ..

TARGET_SRCS = receive.c recvar.c

TARGET_INCLUDES = receive.h recext.h recfun.h rechext.h recstruct.h 

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
