# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = test

BASE_DIRECTORY = ..

TARGET_SRCS = main.c mainapp.c mainproc.c mainvar.c mainwin.c resources.c test.c

TARGET_INCLUDES = mainapp.h mainext.h mainfun.h mainstruct.h mainwin.h test.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)