# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = printman

BASE_DIRECTORY = ..

TARGET_SRCS = printfun.c printman.c printvar.c

TARGET_INCLUDES = printext.h printstruct.h printfun.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
