# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = check_bancali

BASE_DIRECTORY = ..

TARGET_SRCS = main.c mainvar.c mainfun.c mainproc.c mainapp.c mainwin.c gestione_linee.c fine_linea.c chiusura_bancale.c resources.c

TARGET_INCLUDES = chiusura_bancale.h fine_linea.h gestione_linee.h mainapp.h mainext.h mainfun.h mainstruct.h mainwin.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
