# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = barcode

BASE_DIRECTORY = ..

TARGET_SRCS = barcode.c

TARGET_INCLUDES = barcode.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
