# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = tcp_server

BASE_DIRECTORY = ..

TARGET_SRCS = tcp_server.c

TARGET_INCLUDES = 

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
