# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = main

BASE_DIRECTORY = ..

TARGET_SRCS = \
	main.c \
	mainapp.c \
	mainwin.c \
	distribution.c \
	printdist.c \
	calcimballi.c \
	setstatoordine.c \
	spedizionedati.c \
	storicizzazionedati.c \
	caricosettori.c \
	stampaordinecollo.c \
	resetsettore.c \
	ordinifiltrati.c \
	cambiautente.c \
	select.c \
	mainvar.c \
	mainfun.c \
	mainproc.c \
	resources.c

TARGET_INCLUDES = \
	calcimballi.h \
	caricosettori.h \
	cmp_time.h \
	distribution.h \
	mainapp.h \
	mainext.h \
	mainfun.h \
	mainstruct.h \
	mainwin.h \
	ordinifiltrati.h \
	printdist.h \
	resetsettore.h \
	select.h \
	setstatoordine.h \
	spedizionedati.h \
	stampaordinecollo.h \
	storicizzazionedati.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
