# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = printlabel

BASE_DIRECTORY = ..

TARGET_SRCS = printlabel.c printfun.c printutil.c printvar.c printrac.c printxab.c  printxab_A4.c printpacklist.c printdoccons.c printdist.c stampa.c 

TARGET_INCLUDES = printlabel.h printext.h printstruct.h printfun.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
