/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_dlg_exit (void);
GtkWidget* create_dlg_message (void);
GtkWidget* create_dlg_about (void);
GtkWidget* create_dlg_config (void);
GtkWidget* create_dlg_app_error (void);
GtkWidget* create_dlg_trace (void);
GtkWidget* create_dlg_scarti (void);
GtkWidget* create_dlg_storico_scarti (void);
GtkWidget* create_dlg_select_date_range (void);
GtkWidget* create_dlg_barcode (void);
GtkWidget* create_dlg_flags (void);
GtkWidget* create_dlg_work (void);
GtkWidget* create_main_window (void);
GtkWidget* create_dlg_num_copie (void);
