# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = socket_server

BASE_DIRECTORY = ..

TARGET_SRCS = socket_server.c

TARGET_INCLUDES = socket_server.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
