#!/bin/bash
#
# @(#) aoutconv 1.0 Fri Jan 31 15:15:48 MET 1997
#
# Convertitore di formato da COFF a Lynx-A.OUT.
#

TMP1=/tmp/aout-i.$$.o
TMP2=/tmp/aout-o.$$.o

cp $1 $TMP1 || exit 1
strip -g $TMP1 || { rm -f $TMP1; exit 1 }
objcopy -O a.out-i386-lynx $TMP1 $TMP2 || { rm -f $TMP1 $TMP2; exit 1 }
rm -f $TMP1
fixaout $TMP2 $2
rv=$?
rm -f $TMP2
exit $rv
