#!/bin/bash

exec /usr/local/bin/qplc -reset -period 10 -remote-debug \
        -stand-alone -go-anyway -debug  \
	-devconf ios.chkwd=0:ios.trig=0:ios.candebug=255:ios.canspeed=500:ios.bitoffset=48 \
	-no-fault \
            $*
#	-devconf ios.chkwd=0:ios.trig=0:ios.candebug=255:ios.canspeed=500 \
#exec ./qplc -reset -period 10 -remote-debug \
#            -stand-alone -go-anyway -no-hatsh \
#            -devconf ios.chk=0:ios.trig=0 $*

# Per eliminare i segnali di scambio stile CN, aggiungere "-shvmask 0"

