#!/bin/sh
#

/bin/setserial /dev/ttyS4 port 0x1a0 irq 11 \
	autoconfig '^skip_test' fourport \
	set_multiport port1 0x1bf match1 0x0F mask1 0x0F
/bin/setserial /dev/ttyS5 port 0x1a8 irq 11 \
	autoconfig '^skip_test' fourport \
	set_multiport port1 0x1bf match1 0x0F mask1 0x0F
/bin/setserial /dev/ttyS6 port 0x1b0 irq 11 \
	autoconfig '^skip_test' fourport \
	set_multiport port1 0x1bf match1 0x0F mask1 0x0F
/bin/setserial /dev/ttyS7 port 0x1b8 irq 11 \
	autoconfig '^skip_test' fourport \
	set_multiport port1 0x1bf match1 0x0F mask1 0x0F

/bin/setserial /dev/ttyS8 port 0x1c0 irq 10 \
	autoconfig '^skip_test' fourport \
	set_multiport port1 0x1df match1 0x0F mask1 0x0F
/bin/setserial /dev/ttyS9 port 0x1c8 irq 10 \
	autoconfig '^skip_test' fourport \
	set_multiport port1 0x1df match1 0x0F mask1 0x0F
/bin/setserial /dev/ttyS10 port 0x1d0 irq 10 \
	autoconfig '^skip_test' fourport \
	set_multiport port1 0x1df match1 0x0F mask1 0x0F
/bin/setserial /dev/ttyS11 port 0x1d8 irq 10 \
	autoconfig '^skip_test' fourport \
	set_multiport port1 0x1df match1 0x0F mask1 0x0F

