/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

/*
 * Public Functions.
 */

/* Use this function to set the directory containing installed pixmaps. */
void add_pixmap_directory(const gchar *directory);


/*
 * Private Functions.
 */

/* This is used to create the pixmaps in the interface. */
gchar *find_pixmap_file (const gchar *filename);
GdkPixbuf *pixbuf_new(gchar *filename);
GtkWidget* create_pixmap(GtkWidget *widget, gchar *filename);

int set_pixmap(GtkWidget *widget, const gchar *filename);
int gtk_clist_get_first_selected_row(GtkWidget *lst);
#ifdef ELIMINATO
int create_gdk_pixmap(GtkWidget *widget,GdkPixmap **pixmap, GdkBitmap **mask,const gchar *filename);
void free_gdk_pixmap(GdkPixmap *pixmap, GdkBitmap *mask);
#endif
