# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = volum

BASE_DIRECTORY = ..

TARGET_SRCS = volfun.c volum.c volvar.c volutil.c

TARGET_INCLUDES = volum.h volext.h volstruct.h volfun.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
