# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = dbf2sql

BASE_DIRECTORY = ..

TARGET_SRCS = dbf2sql.c ca_file.c dbfun.c

TARGET_INCLUDES = dbf2sql.h ca_file.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
