# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = bilancia

BASE_DIRECTORY = ..

TARGET_SRCS = bilancia.c

TARGET_INCLUDES = bilancia.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
