# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = ios

BASE_DIRECTORY = ..

TARGET_SRCS = ios.c

TARGET_INCLUDES = ios.h

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
