# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = odbc
DEBUG=1
TEST=1

BASE_DIRECTORY = ..

TARGET_SRCS = odbc.c

TARGET_INCLUDES = 

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
