/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gtk/gtk.h>

#include "support.h"

GList *pixmaps_directories = NULL;

/* Use this function to set the directory containing installed pixmaps. */
void add_pixmap_directory (const gchar *directory)
{
  pixmaps_directories = g_list_prepend (pixmaps_directories, g_strdup (directory));
}

/* derived from code build by glade 
*/
gchar *find_pixmap_file (const gchar *filename)
{
	GList *elem;

	if (!filename)
	return NULL;

	/* We step through each of the pixmaps directory to find it. */
	elem = pixmaps_directories;
	while (elem) {
		gchar *pathname = g_strdup_printf ("%s%s%s", (gchar*)elem->data, G_DIR_SEPARATOR_S, filename);

		if (g_file_test (pathname, G_FILE_TEST_EXISTS)){
			return pathname;
		}
		g_free (pathname);
		elem = elem->next;
	}
	return NULL;
}

GdkPixbuf *pixbuf_new(gchar *filename)
{
	GdkPixbuf *pix = NULL;
	gchar *imagefile = NULL;
	gchar *ptr;
	GError *error = NULL;

	g_return_val_if_fail(filename != NULL, NULL);

	if ((g_ascii_strcasecmp(filename, "") == 0)) return NULL;


	if((ptr=rindex(filename,'/'))){
		filename=(ptr+1);
	}

	imagefile = find_pixmap_file(filename);

	if (!imagefile) {
		g_warning ("Couldn't find pixmap file: %s", filename);
		return NULL;
	}

	pix = gdk_pixbuf_new_from_file(imagefile, &error);
	if (!pix) {
		fprintf (stderr, "Failed to load pixbuf file: %s - error: %s\n", filename, error->message);
		g_error_free (error);
	}  

	g_free(imagefile);

	return  pix;
}

GtkWidget* create_pixmap(GtkWidget *widget, gchar *filename)
{
	GdkPixbuf *pixbuf;
	GtkWidget *w;

	w=gtk_image_new ();

	if((pixbuf=pixbuf_new(filename))){
		gtk_image_set_from_pixbuf(GTK_IMAGE(w),pixbuf);
	}
	return w;
}
