# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = settori

BASE_DIRECTORY = ..

TARGET_SRCS = \
settfun.c \
settori.c \
settvar.c

TARGET_INCLUDES = \
settext.h \
settfun.h \
settstruct.h


include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
