# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = fine_linea

BASE_DIRECTORY = ..

TARGET_SRCS = main.c mainapp.c mainfun.c mainproc.c mainvar.c mainwin.c resources.c

TARGET_INCLUDES = mainapp.h  mainext.h  mainfun.h  mainstruct.h  mainwin.h 

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
