/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_dlg_about (void);
GtkWidget* create_dlg_config (void);
GtkWidget* create_dlg_ingresso_merce (void);
GtkWidget* create_dlg_spedizione_merce (void);
GtkWidget* create_dlg_conteggia_prodotto (void);
GtkWidget* create_dlg_inserimento_distinta (void);
GtkWidget* create_dlg_edit_prodotto (void);
GtkWidget* create_dlg_inserisci_qta (void);
GtkWidget* create_dlg_importazione_spedizioni (void);
GtkWidget* create_dlg_importazione_catalogo (void);
GtkWidget* create_dlg_lista (void);
GtkWidget* create_dlg_insert_prodotto (void);
GtkWidget* create_dlg_insert_udc (void);
GtkWidget* create_dlg_differenza_inventariale (void);
GtkWidget* create_dlg_edit_bancale (void);
GtkWidget* create_dlg_edit_distinta (void);
