/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dlg_about (void)
{
  GtkWidget *dlg_about;
  GtkWidget *vbox2;
  GtkWidget *hbox1;
  GtkWidget *frame6;
  GtkWidget *eb_logo;
  GtkWidget *hbox190;
  GtkWidget *pixmap253;
  GtkWidget *image5;
  GtkWidget *hbox182;
  GtkWidget *image3;
  GtkWidget *image4;
  GtkWidget *frame1;
  GtkWidget *vbox3;
  GtkWidget *table25;
  GtkWidget *label646;
  GtkWidget *label647;
  GtkWidget *label648;
  GtkWidget *frame230;
  GtkWidget *lb_version;
  GtkWidget *frame231;
  GtkWidget *lb_customer;
  GtkWidget *frame232;
  GtkWidget *lb_rcsid;
  GtkWidget *label1223;
  GtkWidget *label1224;
  GtkWidget *frame534;
  GtkWidget *lb_authors;
  GtkWidget *frame535;
  GtkWidget *lb_copyright;
  GtkWidget *hseparator10;
  GtkWidget *hbuttonbox2;
  GtkWidget *pb_ok;

  dlg_about = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (dlg_about, "dlg_about");
  gtk_window_set_title (GTK_WINDOW (dlg_about), _("About CNi Easy Picking"));
  gtk_window_set_position (GTK_WINDOW (dlg_about), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (dlg_about), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dlg_about), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (dlg_about), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (dlg_about), vbox2);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 5);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame6, "frame6");
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (hbox1), frame6, TRUE, TRUE, 0);

  eb_logo = gtk_event_box_new ();
  gtk_widget_set_name (eb_logo, "eb_logo");
  gtk_widget_show (eb_logo);
  gtk_container_add (GTK_CONTAINER (frame6), eb_logo);

  hbox190 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox190, "hbox190");
  gtk_widget_show (hbox190);
  gtk_container_add (GTK_CONTAINER (eb_logo), hbox190);

  pixmap253 = create_pixmap (dlg_about, "test/AEL-GLOSSY-small.png");
  gtk_widget_set_name (pixmap253, "pixmap253");
  gtk_widget_show (pixmap253);
  gtk_box_pack_start (GTK_BOX (hbox190), pixmap253, TRUE, TRUE, 0);

  image5 = create_pixmap (dlg_about, "test/easy-picking.png");
  gtk_widget_set_name (image5, "image5");
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox190), image5, TRUE, TRUE, 0);

  hbox182 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox182, "hbox182");
  gtk_widget_show (hbox182);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox182, TRUE, TRUE, 0);

  image3 = create_pixmap (dlg_about, "test/gnome-logo-small.png");
  gtk_widget_set_name (image3, "image3");
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox182), image3, TRUE, TRUE, 0);

  image4 = create_pixmap (dlg_about, "test/postgresql.png");
  gtk_widget_set_name (image4, "image4");
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox182), image4, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox2), frame1, FALSE, FALSE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);
  gtk_frame_set_label_align (GTK_FRAME (frame1), 0.5, 0.5);

  vbox3 = gtk_vbox_new (FALSE, 5);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame1), vbox3);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 5);

  table25 = gtk_table_new (5, 2, FALSE);
  gtk_widget_set_name (table25, "table25");
  gtk_widget_show (table25);
  gtk_box_pack_start (GTK_BOX (vbox3), table25, FALSE, FALSE, 2);
  gtk_table_set_row_spacings (GTK_TABLE (table25), 2);

  label646 = gtk_label_new (_("Version"));
  gtk_widget_set_name (label646, "label646");
  gtk_widget_show (label646);
  gtk_table_attach (GTK_TABLE (table25), label646, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label646), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label646), 0, 0.5);

  label647 = gtk_label_new (_("Customer Name"));
  gtk_widget_set_name (label647, "label647");
  gtk_widget_show (label647);
  gtk_table_attach (GTK_TABLE (table25), label647, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label647), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label647), 0, 0.5);

  label648 = gtk_label_new (_("RCSID String"));
  gtk_widget_set_name (label648, "label648");
  gtk_widget_show (label648);
  gtk_table_attach (GTK_TABLE (table25), label648, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label648), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label648), 0, 0.5);

  frame230 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame230, "frame230");
  gtk_widget_show (frame230);
  gtk_table_attach (GTK_TABLE (table25), frame230, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_version = gtk_label_new ("");
  gtk_widget_set_name (lb_version, "lb_version");
  gtk_widget_show (lb_version);
  gtk_container_add (GTK_CONTAINER (frame230), lb_version);
  gtk_label_set_use_markup (GTK_LABEL (lb_version), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_version), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_version), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_version), 2, 0);

  frame231 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame231, "frame231");
  gtk_widget_show (frame231);
  gtk_table_attach (GTK_TABLE (table25), frame231, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_customer = gtk_label_new ("");
  gtk_widget_set_name (lb_customer, "lb_customer");
  gtk_widget_show (lb_customer);
  gtk_container_add (GTK_CONTAINER (frame231), lb_customer);
  gtk_label_set_use_markup (GTK_LABEL (lb_customer), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_customer), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_customer), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_customer), 2, 0);

  frame232 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame232, "frame232");
  gtk_widget_show (frame232);
  gtk_table_attach (GTK_TABLE (table25), frame232, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);

  lb_rcsid = gtk_label_new ("");
  gtk_widget_set_name (lb_rcsid, "lb_rcsid");
  gtk_widget_show (lb_rcsid);
  gtk_container_add (GTK_CONTAINER (frame232), lb_rcsid);
  gtk_label_set_use_markup (GTK_LABEL (lb_rcsid), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_rcsid), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_rcsid), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_rcsid), 2, 0);

  label1223 = gtk_label_new (_("Authors"));
  gtk_widget_set_name (label1223, "label1223");
  gtk_widget_show (label1223);
  gtk_table_attach (GTK_TABLE (table25), label1223, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1223), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label1223), 0, 0.5);

  label1224 = gtk_label_new (_("Copyright"));
  gtk_widget_set_name (label1224, "label1224");
  gtk_widget_show (label1224);
  gtk_table_attach (GTK_TABLE (table25), label1224, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1224), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label1224), 0, 0.5);

  frame534 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame534, "frame534");
  gtk_widget_show (frame534);
  gtk_table_attach (GTK_TABLE (table25), frame534, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_authors = gtk_label_new ("");
  gtk_widget_set_name (lb_authors, "lb_authors");
  gtk_widget_show (lb_authors);
  gtk_container_add (GTK_CONTAINER (frame534), lb_authors);
  gtk_label_set_use_markup (GTK_LABEL (lb_authors), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_authors), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_authors), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_authors), 2, 0);

  frame535 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame535, "frame535");
  gtk_widget_show (frame535);
  gtk_table_attach (GTK_TABLE (table25), frame535, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lb_copyright = gtk_label_new ("");
  gtk_widget_set_name (lb_copyright, "lb_copyright");
  gtk_widget_show (lb_copyright);
  gtk_container_add (GTK_CONTAINER (frame535), lb_copyright);
  gtk_label_set_use_markup (GTK_LABEL (lb_copyright), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_copyright), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_copyright), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lb_copyright), 2, 0);

  hseparator10 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator10, "hseparator10");
  gtk_widget_show (hseparator10);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator10, TRUE, TRUE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox2, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_SPREAD);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox2), 30);

  pb_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (pb_ok, "pb_ok");
  gtk_widget_show (pb_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), pb_ok);
  GTK_WIDGET_SET_FLAGS (pb_ok, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) pb_ok, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dlg_about));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_about, dlg_about, "dlg_about");
  GLADE_HOOKUP_OBJECT (dlg_about, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (dlg_about, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (dlg_about, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (dlg_about, eb_logo, "eb_logo");
  GLADE_HOOKUP_OBJECT (dlg_about, hbox190, "hbox190");
  GLADE_HOOKUP_OBJECT (dlg_about, pixmap253, "pixmap253");
  GLADE_HOOKUP_OBJECT (dlg_about, image5, "image5");
  GLADE_HOOKUP_OBJECT (dlg_about, hbox182, "hbox182");
  GLADE_HOOKUP_OBJECT (dlg_about, image3, "image3");
  GLADE_HOOKUP_OBJECT (dlg_about, image4, "image4");
  GLADE_HOOKUP_OBJECT (dlg_about, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (dlg_about, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (dlg_about, table25, "table25");
  GLADE_HOOKUP_OBJECT (dlg_about, label646, "label646");
  GLADE_HOOKUP_OBJECT (dlg_about, label647, "label647");
  GLADE_HOOKUP_OBJECT (dlg_about, label648, "label648");
  GLADE_HOOKUP_OBJECT (dlg_about, frame230, "frame230");
  GLADE_HOOKUP_OBJECT (dlg_about, lb_version, "lb_version");
  GLADE_HOOKUP_OBJECT (dlg_about, frame231, "frame231");
  GLADE_HOOKUP_OBJECT (dlg_about, lb_customer, "lb_customer");
  GLADE_HOOKUP_OBJECT (dlg_about, frame232, "frame232");
  GLADE_HOOKUP_OBJECT (dlg_about, lb_rcsid, "lb_rcsid");
  GLADE_HOOKUP_OBJECT (dlg_about, label1223, "label1223");
  GLADE_HOOKUP_OBJECT (dlg_about, label1224, "label1224");
  GLADE_HOOKUP_OBJECT (dlg_about, frame534, "frame534");
  GLADE_HOOKUP_OBJECT (dlg_about, lb_authors, "lb_authors");
  GLADE_HOOKUP_OBJECT (dlg_about, frame535, "frame535");
  GLADE_HOOKUP_OBJECT (dlg_about, lb_copyright, "lb_copyright");
  GLADE_HOOKUP_OBJECT (dlg_about, hseparator10, "hseparator10");
  GLADE_HOOKUP_OBJECT (dlg_about, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (dlg_about, pb_ok, "pb_ok");

  return dlg_about;
}

GtkWidget*
create_dlg_exit (void)
{
  GtkWidget *dlg_exit;
  GtkWidget *vbox4;
  GtkWidget *frame7;
  GtkWidget *hbox3;
  GtkWidget *pixmap4;
  GtkWidget *label9;
  GtkWidget *hseparator1;
  GtkWidget *hbuttonbox1;
  GtkWidget *pb_ok;
  GtkWidget *pb_cancel;

  dlg_exit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (dlg_exit, "dlg_exit");
  gtk_container_set_border_width (GTK_CONTAINER (dlg_exit), 5);
  gtk_window_set_title (GTK_WINDOW (dlg_exit), _("Exit Application"));
  gtk_window_set_position (GTK_WINDOW (dlg_exit), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (dlg_exit), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dlg_exit), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (dlg_exit), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox4 = gtk_vbox_new (FALSE, 5);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (dlg_exit), vbox4);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame7, "frame7");
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox4), frame7, TRUE, TRUE, 0);

  hbox3 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (frame7), hbox3);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 5);

  pixmap4 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_set_name (pixmap4, "pixmap4");
  gtk_widget_show (pixmap4);
  gtk_box_pack_start (GTK_BOX (hbox3), pixmap4, FALSE, FALSE, 0);

  label9 = gtk_label_new (_("<b>Uscita dall'applicazione</b>\n\tConfermando questa opzione\n\tl'applicazione verra' terminata.\n\t"));
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox3), label9, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label9), 0.1, 0.5);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox4), hseparator1, FALSE, FALSE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox1, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 30);

  pb_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (pb_ok, "pb_ok");
  gtk_widget_show (pb_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), pb_ok);
  GTK_WIDGET_SET_FLAGS (pb_ok, GTK_CAN_DEFAULT);

  pb_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (pb_cancel, "pb_cancel");
  gtk_widget_show (pb_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), pb_cancel);
  GTK_WIDGET_SET_FLAGS (pb_cancel, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) pb_ok, "clicked",
                            G_CALLBACK (on_dlg_exit_pb_ok_clicked),
                            GTK_OBJECT (dlg_exit));
  g_signal_connect_swapped ((gpointer) pb_cancel, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dlg_exit));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_exit, dlg_exit, "dlg_exit");
  GLADE_HOOKUP_OBJECT (dlg_exit, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (dlg_exit, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (dlg_exit, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (dlg_exit, pixmap4, "pixmap4");
  GLADE_HOOKUP_OBJECT (dlg_exit, label9, "label9");
  GLADE_HOOKUP_OBJECT (dlg_exit, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (dlg_exit, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (dlg_exit, pb_ok, "pb_ok");
  GLADE_HOOKUP_OBJECT (dlg_exit, pb_cancel, "pb_cancel");

  return dlg_exit;
}

GtkWidget*
create_dlg_message (void)
{
  GtkWidget *dlg_message;
  GtkWidget *vbox5;
  GtkWidget *frame8;
  GtkWidget *hbox4;
  GtkWidget *pixmap5;
  GtkWidget *lb_msg;
  GtkWidget *hseparator3;
  GtkWidget *hbuttonbox3;
  GtkWidget *pb_ok;
  GtkWidget *pb_cancel;

  dlg_message = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (dlg_message, "dlg_message");
  gtk_container_set_border_width (GTK_CONTAINER (dlg_message), 5);
  gtk_window_set_title (GTK_WINDOW (dlg_message), _("Messaggio dell'applicazione"));
  gtk_window_set_position (GTK_WINDOW (dlg_message), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (dlg_message), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dlg_message), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (dlg_message), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox5 = gtk_vbox_new (FALSE, 5);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (dlg_message), vbox5);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame8, "frame8");
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (vbox5), frame8, TRUE, TRUE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (frame8), hbox4);
  gtk_container_set_border_width (GTK_CONTAINER (hbox4), 5);

  pixmap5 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_DIALOG);
  gtk_widget_set_name (pixmap5, "pixmap5");
  gtk_widget_show (pixmap5);
  gtk_box_pack_start (GTK_BOX (hbox4), pixmap5, FALSE, FALSE, 0);

  lb_msg = gtk_label_new (_("\t"));
  gtk_widget_set_name (lb_msg, "lb_msg");
  gtk_widget_show (lb_msg);
  gtk_box_pack_start (GTK_BOX (hbox4), lb_msg, TRUE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (lb_msg), TRUE);
  gtk_label_set_justify (GTK_LABEL (lb_msg), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (lb_msg), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lb_msg), 0.1, 0.5);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator3, "hseparator3");
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox5), hseparator3, FALSE, FALSE, 0);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox3, "hbuttonbox3");
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox5), hbuttonbox3, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_SPREAD);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox3), 30);

  pb_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (pb_ok, "pb_ok");
  gtk_widget_show (pb_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), pb_ok);
  GTK_WIDGET_SET_FLAGS (pb_ok, GTK_CAN_DEFAULT);

  pb_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (pb_cancel, "pb_cancel");
  gtk_widget_show (pb_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), pb_cancel);
  GTK_WIDGET_SET_FLAGS (pb_cancel, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) pb_cancel, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dlg_message));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_message, dlg_message, "dlg_message");
  GLADE_HOOKUP_OBJECT (dlg_message, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (dlg_message, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (dlg_message, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (dlg_message, pixmap5, "pixmap5");
  GLADE_HOOKUP_OBJECT (dlg_message, lb_msg, "lb_msg");
  GLADE_HOOKUP_OBJECT (dlg_message, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (dlg_message, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (dlg_message, pb_ok, "pb_ok");
  GLADE_HOOKUP_OBJECT (dlg_message, pb_cancel, "pb_cancel");

  return dlg_message;
}

GtkWidget*
create_dlg_config (void)
{
  GtkWidget *dlg_config;
  GtkWidget *vbox12;
  GtkWidget *vbox63;
  GtkWidget *frame229;
  GtkWidget *vbox361;
  GtkWidget *table29;
  GtkWidget *label693;
  GtkObject *sb_debug_version_adj;
  GtkWidget *sb_debug_version;
  GtkWidget *label699;
  GtkObject *sb_column_width_adj;
  GtkWidget *sb_column_width;
  GtkWidget *hbox160;
  GtkWidget *label694;
  GtkWidget *entry_printer;
  GtkWidget *label1225;
  GtkWidget *frame164;
  GtkWidget *table22;
  GtkWidget *entry_data_path;
  GtkWidget *entry_exe_path;
  GtkWidget *entry_print_path;
  GtkWidget *label543;
  GtkWidget *label544;
  GtkWidget *label545;
  GtkWidget *label1226;
  GtkWidget *frame156;
  GtkWidget *table11;
  GtkWidget *entry_pghost;
  GtkWidget *entry_pgport;
  GtkWidget *entry_pgdatabase;
  GtkWidget *lb_pghost;
  GtkWidget *lb_pgport;
  GtkWidget *lb_pgdatabase;
  GtkWidget *label1227;
  GtkWidget *hseparator8;
  GtkWidget *hbuttonbox8;
  GtkWidget *pb_ok;
  GtkWidget *pb_apply;
  GtkWidget *pb_cancel;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  dlg_config = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (dlg_config, "dlg_config");
  gtk_container_set_border_width (GTK_CONTAINER (dlg_config), 5);
  gtk_window_set_title (GTK_WINDOW (dlg_config), _("Preferences"));
  gtk_window_set_modal (GTK_WINDOW (dlg_config), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (dlg_config), 600, 300);

  vbox12 = gtk_vbox_new (FALSE, 5);
  gtk_widget_set_name (vbox12, "vbox12");
  gtk_widget_show (vbox12);
  gtk_container_add (GTK_CONTAINER (dlg_config), vbox12);

  vbox63 = gtk_vbox_new (FALSE, 3);
  gtk_widget_set_name (vbox63, "vbox63");
  gtk_widget_show (vbox63);
  gtk_box_pack_start (GTK_BOX (vbox12), vbox63, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox63), 5);

  frame229 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame229, "frame229");
  gtk_widget_show (frame229);
  gtk_box_pack_start (GTK_BOX (vbox63), frame229, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame229), 5);

  vbox361 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox361, "vbox361");
  gtk_widget_show (vbox361);
  gtk_container_add (GTK_CONTAINER (frame229), vbox361);

  table29 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table29, "table29");
  gtk_widget_show (table29);
  gtk_box_pack_start (GTK_BOX (vbox361), table29, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table29), 3);
  gtk_table_set_row_spacings (GTK_TABLE (table29), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table29), 3);

  label693 = gtk_label_new (_("Debug Version"));
  gtk_widget_set_name (label693, "label693");
  gtk_widget_show (label693);
  gtk_table_attach (GTK_TABLE (table29), label693, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label693), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label693), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label693), 10, 0);

  sb_debug_version_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  sb_debug_version = gtk_spin_button_new (GTK_ADJUSTMENT (sb_debug_version_adj), 1, 0);
  gtk_widget_set_name (sb_debug_version, "sb_debug_version");
  gtk_widget_show (sb_debug_version);
  gtk_table_attach (GTK_TABLE (table29), sb_debug_version, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label699 = gtk_label_new (_("Fattore di larghezza delle colonne"));
  gtk_widget_set_name (label699, "label699");
  gtk_widget_show (label699);
  gtk_table_attach (GTK_TABLE (table29), label699, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label699), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label699), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label699), 10, 0);

  sb_column_width_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  sb_column_width = gtk_spin_button_new (GTK_ADJUSTMENT (sb_column_width_adj), 1, 0);
  gtk_widget_set_name (sb_column_width, "sb_column_width");
  gtk_widget_show (sb_column_width);
  gtk_table_attach (GTK_TABLE (table29), sb_column_width, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox160 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox160, "hbox160");
  gtk_widget_show (hbox160);
  gtk_box_pack_start (GTK_BOX (vbox361), hbox160, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox160), 4);

  label694 = gtk_label_new (_("Stampante"));
  gtk_widget_set_name (label694, "label694");
  gtk_widget_show (label694);
  gtk_box_pack_start (GTK_BOX (hbox160), label694, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label694), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label694), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label694), 10, 0);

  entry_printer = gtk_entry_new ();
  gtk_widget_set_name (entry_printer, "entry_printer");
  gtk_widget_show (entry_printer);
  gtk_box_pack_start (GTK_BOX (hbox160), entry_printer, FALSE, TRUE, 0);

  label1225 = gtk_label_new (_("General"));
  gtk_widget_set_name (label1225, "label1225");
  gtk_widget_show (label1225);
  gtk_frame_set_label_widget (GTK_FRAME (frame229), label1225);

  frame164 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame164, "frame164");
  gtk_widget_show (frame164);
  gtk_box_pack_start (GTK_BOX (vbox63), frame164, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame164), 5);

  table22 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table22, "table22");
  gtk_widget_show (table22);
  gtk_container_add (GTK_CONTAINER (frame164), table22);
  gtk_container_set_border_width (GTK_CONTAINER (table22), 3);
  gtk_table_set_row_spacings (GTK_TABLE (table22), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table22), 3);

  entry_data_path = gtk_entry_new ();
  gtk_widget_set_name (entry_data_path, "entry_data_path");
  gtk_widget_show (entry_data_path);
  gtk_table_attach (GTK_TABLE (table22), entry_data_path, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_exe_path = gtk_entry_new ();
  gtk_widget_set_name (entry_exe_path, "entry_exe_path");
  gtk_widget_show (entry_exe_path);
  gtk_table_attach (GTK_TABLE (table22), entry_exe_path, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_print_path = gtk_entry_new ();
  gtk_widget_set_name (entry_print_path, "entry_print_path");
  gtk_widget_show (entry_print_path);
  gtk_table_attach (GTK_TABLE (table22), entry_print_path, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label543 = gtk_label_new (_("Dati di configurazione"));
  gtk_widget_set_name (label543, "label543");
  gtk_widget_show (label543);
  gtk_table_attach (GTK_TABLE (table22), label543, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label543), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label543), 0, 0.5);

  label544 = gtk_label_new (_("Processi Eseguibili"));
  gtk_widget_set_name (label544, "label544");
  gtk_widget_show (label544);
  gtk_table_attach (GTK_TABLE (table22), label544, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label544), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label544), 0, 0.5);

  label545 = gtk_label_new (_("Directory di stampa"));
  gtk_widget_set_name (label545, "label545");
  gtk_widget_show (label545);
  gtk_table_attach (GTK_TABLE (table22), label545, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label545), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label545), 0, 0.5);

  label1226 = gtk_label_new (_("Directories"));
  gtk_widget_set_name (label1226, "label1226");
  gtk_widget_show (label1226);
  gtk_frame_set_label_widget (GTK_FRAME (frame164), label1226);

  frame156 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame156, "frame156");
  gtk_widget_show (frame156);
  gtk_box_pack_start (GTK_BOX (vbox63), frame156, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame156), 5);

  table11 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table11, "table11");
  gtk_widget_show (table11);
  gtk_container_add (GTK_CONTAINER (frame156), table11);
  gtk_container_set_border_width (GTK_CONTAINER (table11), 3);
  gtk_table_set_row_spacings (GTK_TABLE (table11), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table11), 3);

  entry_pghost = gtk_entry_new ();
  gtk_widget_set_name (entry_pghost, "entry_pghost");
  gtk_widget_show (entry_pghost);
  gtk_table_attach (GTK_TABLE (table11), entry_pghost, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_pgport = gtk_entry_new ();
  gtk_widget_set_name (entry_pgport, "entry_pgport");
  gtk_widget_show (entry_pgport);
  gtk_table_attach (GTK_TABLE (table11), entry_pgport, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_pgdatabase = gtk_entry_new ();
  gtk_widget_set_name (entry_pgdatabase, "entry_pgdatabase");
  gtk_widget_show (entry_pgdatabase);
  gtk_table_attach (GTK_TABLE (table11), entry_pgdatabase, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_pghost = gtk_label_new (_("PGHost"));
  gtk_widget_set_name (lb_pghost, "lb_pghost");
  gtk_widget_show (lb_pghost);
  gtk_table_attach (GTK_TABLE (table11), lb_pghost, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lb_pghost), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_pghost), 0, 0.5);

  lb_pgport = gtk_label_new (_("PGPort"));
  gtk_widget_set_name (lb_pgport, "lb_pgport");
  gtk_widget_show (lb_pgport);
  gtk_table_attach (GTK_TABLE (table11), lb_pgport, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lb_pgport), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_pgport), 0, 0.5);

  lb_pgdatabase = gtk_label_new (_("PGDataBase"));
  gtk_widget_set_name (lb_pgdatabase, "lb_pgdatabase");
  gtk_widget_show (lb_pgdatabase);
  gtk_table_attach (GTK_TABLE (table11), lb_pgdatabase, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lb_pgdatabase), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_pgdatabase), 0, 0.5);

  label1227 = gtk_label_new (_("Database"));
  gtk_widget_set_name (label1227, "label1227");
  gtk_widget_show (label1227);
  gtk_frame_set_label_widget (GTK_FRAME (frame156), label1227);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator8, "hseparator8");
  gtk_widget_show (hseparator8);
  gtk_box_pack_start (GTK_BOX (vbox12), hseparator8, FALSE, FALSE, 0);

  hbuttonbox8 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox8, "hbuttonbox8");
  gtk_widget_show (hbuttonbox8);
  gtk_box_pack_start (GTK_BOX (vbox12), hbuttonbox8, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox8), GTK_BUTTONBOX_SPREAD);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox8), 30);

  pb_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (pb_ok, "pb_ok");
  gtk_widget_show (pb_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), pb_ok);
  GTK_WIDGET_SET_FLAGS (pb_ok, GTK_CAN_DEFAULT);

  pb_apply = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (pb_apply, "pb_apply");
  gtk_widget_show (pb_apply);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), pb_apply);
  GTK_WIDGET_SET_FLAGS (pb_apply, GTK_CAN_DEFAULT);

  pb_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (pb_cancel, "pb_cancel");
  gtk_widget_show (pb_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), pb_cancel);
  GTK_WIDGET_SET_FLAGS (pb_cancel, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (pb_cancel, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect_swapped ((gpointer) pb_ok, "clicked",
                            G_CALLBACK (on_dlg_config_pb_ok_clicked),
                            GTK_OBJECT (dlg_config));
  g_signal_connect_swapped ((gpointer) pb_apply, "clicked",
                            G_CALLBACK (on_dlg_config_pb_apply_clicked),
                            GTK_OBJECT (dlg_config));
  g_signal_connect_swapped ((gpointer) pb_cancel, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dlg_config));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_config, dlg_config, "dlg_config");
  GLADE_HOOKUP_OBJECT (dlg_config, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (dlg_config, vbox63, "vbox63");
  GLADE_HOOKUP_OBJECT (dlg_config, frame229, "frame229");
  GLADE_HOOKUP_OBJECT (dlg_config, vbox361, "vbox361");
  GLADE_HOOKUP_OBJECT (dlg_config, table29, "table29");
  GLADE_HOOKUP_OBJECT (dlg_config, label693, "label693");
  GLADE_HOOKUP_OBJECT (dlg_config, sb_debug_version, "sb_debug_version");
  GLADE_HOOKUP_OBJECT (dlg_config, label699, "label699");
  GLADE_HOOKUP_OBJECT (dlg_config, sb_column_width, "sb_column_width");
  GLADE_HOOKUP_OBJECT (dlg_config, hbox160, "hbox160");
  GLADE_HOOKUP_OBJECT (dlg_config, label694, "label694");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_printer, "entry_printer");
  GLADE_HOOKUP_OBJECT (dlg_config, label1225, "label1225");
  GLADE_HOOKUP_OBJECT (dlg_config, frame164, "frame164");
  GLADE_HOOKUP_OBJECT (dlg_config, table22, "table22");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_data_path, "entry_data_path");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_exe_path, "entry_exe_path");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_print_path, "entry_print_path");
  GLADE_HOOKUP_OBJECT (dlg_config, label543, "label543");
  GLADE_HOOKUP_OBJECT (dlg_config, label544, "label544");
  GLADE_HOOKUP_OBJECT (dlg_config, label545, "label545");
  GLADE_HOOKUP_OBJECT (dlg_config, label1226, "label1226");
  GLADE_HOOKUP_OBJECT (dlg_config, frame156, "frame156");
  GLADE_HOOKUP_OBJECT (dlg_config, table11, "table11");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_pghost, "entry_pghost");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_pgport, "entry_pgport");
  GLADE_HOOKUP_OBJECT (dlg_config, entry_pgdatabase, "entry_pgdatabase");
  GLADE_HOOKUP_OBJECT (dlg_config, lb_pghost, "lb_pghost");
  GLADE_HOOKUP_OBJECT (dlg_config, lb_pgport, "lb_pgport");
  GLADE_HOOKUP_OBJECT (dlg_config, lb_pgdatabase, "lb_pgdatabase");
  GLADE_HOOKUP_OBJECT (dlg_config, label1227, "label1227");
  GLADE_HOOKUP_OBJECT (dlg_config, hseparator8, "hseparator8");
  GLADE_HOOKUP_OBJECT (dlg_config, hbuttonbox8, "hbuttonbox8");
  GLADE_HOOKUP_OBJECT (dlg_config, pb_ok, "pb_ok");
  GLADE_HOOKUP_OBJECT (dlg_config, pb_apply, "pb_apply");
  GLADE_HOOKUP_OBJECT (dlg_config, pb_cancel, "pb_cancel");

  gtk_window_add_accel_group (GTK_WINDOW (dlg_config), accel_group);

  return dlg_config;
}

GtkWidget*
create_dlg_test (void)
{
  GtkWidget *dlg_test;
  GtkWidget *vbox371;
  GtkWidget *frame536;
  GtkWidget *vbox374;
  GtkWidget *hbox187;
  GtkWidget *frame537;
  GtkWidget *vbox375;
  GtkWidget *rb_tutti_i_settori;
  GSList *rb_tutti_i_settori_group = NULL;
  GtkWidget *hbox184;
  GtkWidget *rb_singolo_settore;
  GtkWidget *hbox185;
  GtkWidget *lb_settore;
  GtkObject *sb_settore_adj;
  GtkWidget *sb_settore;
  GtkWidget *label1228;
  GtkWidget *frame541;
  GtkWidget *vbox379;
  GtkWidget *rb_priorita;
  GSList *rb_priorita_group = NULL;
  GtkWidget *rb_ubicazione;
  GtkWidget *label1229;
  GtkWidget *hbox186;
  GtkWidget *frame538;
  GtkWidget *vbox376;
  GtkWidget *rb_attesa_pulsante;
  GSList *rb_attesa_pulsante_group = NULL;
  GtkWidget *hbox188;
  GtkWidget *rb_pulsante_simulato;
  GtkWidget *hbox189;
  GtkWidget *label1230b;
  GtkObject *sb_delay_adj;
  GtkWidget *sb_delay;
  GtkWidget *label1230;
  GtkWidget *frame539;
  GtkWidget *tb_ciclo_infinito;
  GtkWidget *label1231;
  GtkWidget *sw_list;
  GtkWidget *frame540;
  GtkWidget *lb_msg;
  GtkWidget *hseparator11;
  GtkWidget *hbuttonbox9;
  GtkWidget *pb_start;
  GtkWidget *vbox372;
  GtkWidget *pixmap256;
  GtkWidget *label1226;
  GtkWidget *pb_stop;
  GtkWidget *vbox373;
  GtkWidget *pixmap257;
  GtkWidget *label1227;
  GtkWidget *pb_reset;
  GtkWidget *vbox377;
  GtkWidget *pixmap258;
  GtkWidget *label1228b;
  GtkWidget *pb_cancel;
  GtkWidget *vbox378;
  GtkWidget *pixmap259;
  GtkWidget *label1229b;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  dlg_test = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (dlg_test, "dlg_test");
  gtk_container_set_border_width (GTK_CONTAINER (dlg_test), 5);
  gtk_window_set_title (GTK_WINDOW (dlg_test), _("Modalita' di test"));
  gtk_window_set_modal (GTK_WINDOW (dlg_test), TRUE);

  vbox371 = gtk_vbox_new (FALSE, 5);
  gtk_widget_set_name (vbox371, "vbox371");
  gtk_widget_show (vbox371);
  gtk_container_add (GTK_CONTAINER (dlg_test), vbox371);

  frame536 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame536, "frame536");
  gtk_widget_show (frame536);
  gtk_box_pack_start (GTK_BOX (vbox371), frame536, TRUE, TRUE, 0);

  vbox374 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox374, "vbox374");
  gtk_widget_show (vbox374);
  gtk_container_add (GTK_CONTAINER (frame536), vbox374);

  hbox187 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox187, "hbox187");
  gtk_widget_show (hbox187);
  gtk_box_pack_start (GTK_BOX (vbox374), hbox187, FALSE, FALSE, 0);

  frame537 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame537, "frame537");
  gtk_widget_show (frame537);
  gtk_box_pack_start (GTK_BOX (hbox187), frame537, TRUE, TRUE, 0);

  vbox375 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox375, "vbox375");
  gtk_widget_show (vbox375);
  gtk_container_add (GTK_CONTAINER (frame537), vbox375);

  rb_tutti_i_settori = gtk_radio_button_new_with_mnemonic (NULL, _("_Tutti i settori"));
  gtk_widget_set_name (rb_tutti_i_settori, "rb_tutti_i_settori");
  gtk_widget_show (rb_tutti_i_settori);
  gtk_box_pack_start (GTK_BOX (vbox375), rb_tutti_i_settori, TRUE, TRUE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_tutti_i_settori), rb_tutti_i_settori_group);
  rb_tutti_i_settori_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_tutti_i_settori));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (rb_tutti_i_settori), TRUE);

  hbox184 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox184, "hbox184");
  gtk_widget_show (hbox184);
  gtk_box_pack_start (GTK_BOX (vbox375), hbox184, TRUE, FALSE, 0);

  rb_singolo_settore = gtk_radio_button_new_with_mnemonic (NULL, _("S_ingolo Settore"));
  gtk_widget_set_name (rb_singolo_settore, "rb_singolo_settore");
  gtk_widget_show (rb_singolo_settore);
  gtk_box_pack_start (GTK_BOX (hbox184), rb_singolo_settore, TRUE, TRUE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_singolo_settore), rb_tutti_i_settori_group);
  rb_tutti_i_settori_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_singolo_settore));

  hbox185 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox185, "hbox185");
  gtk_widget_show (hbox185);
  gtk_box_pack_start (GTK_BOX (hbox184), hbox185, TRUE, TRUE, 0);

  lb_settore = gtk_label_new (_("Settore"));
  gtk_widget_set_name (lb_settore, "lb_settore");
  gtk_widget_show (lb_settore);
  gtk_box_pack_start (GTK_BOX (hbox185), lb_settore, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (lb_settore), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lb_settore), 0, 0.5);

  sb_settore_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  sb_settore = gtk_spin_button_new (GTK_ADJUSTMENT (sb_settore_adj), 1, 0);
  gtk_widget_set_name (sb_settore, "sb_settore");
  gtk_widget_show (sb_settore);
  gtk_box_pack_start (GTK_BOX (hbox185), sb_settore, TRUE, TRUE, 0);

  label1228 = gtk_label_new (_("Settori da testare"));
  gtk_widget_set_name (label1228, "label1228");
  gtk_widget_show (label1228);
  gtk_frame_set_label_widget (GTK_FRAME (frame537), label1228);

  frame541 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame541, "frame541");
  gtk_widget_show (frame541);
  gtk_box_pack_start (GTK_BOX (hbox187), frame541, TRUE, TRUE, 0);

  vbox379 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox379, "vbox379");
  gtk_widget_show (vbox379);
  gtk_container_add (GTK_CONTAINER (frame541), vbox379);

  rb_priorita = gtk_radio_button_new_with_mnemonic (NULL, _("_Priorita'"));
  gtk_widget_set_name (rb_priorita, "rb_priorita");
  gtk_widget_show (rb_priorita);
  gtk_box_pack_start (GTK_BOX (vbox379), rb_priorita, TRUE, TRUE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_priorita), rb_priorita_group);
  rb_priorita_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_priorita));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (rb_priorita), TRUE);

  rb_ubicazione = gtk_radio_button_new_with_mnemonic (NULL, _("_Ubicazione"));
  gtk_widget_set_name (rb_ubicazione, "rb_ubicazione");
  gtk_widget_show (rb_ubicazione);
  gtk_box_pack_start (GTK_BOX (vbox379), rb_ubicazione, TRUE, TRUE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_ubicazione), rb_priorita_group);
  rb_priorita_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_ubicazione));

  label1229 = gtk_label_new (_("Ordinamento"));
  gtk_widget_set_name (label1229, "label1229");
  gtk_widget_show (label1229);
  gtk_frame_set_label_widget (GTK_FRAME (frame541), label1229);

  hbox186 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox186, "hbox186");
  gtk_widget_show (hbox186);
  gtk_box_pack_start (GTK_BOX (vbox374), hbox186, FALSE, FALSE, 0);

  frame538 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame538, "frame538");
  gtk_widget_show (frame538);
  gtk_box_pack_start (GTK_BOX (hbox186), frame538, TRUE, TRUE, 0);

  vbox376 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox376, "vbox376");
  gtk_widget_show (vbox376);
  gtk_container_add (GTK_CONTAINER (frame538), vbox376);

  rb_attesa_pulsante = gtk_radio_button_new_with_mnemonic (NULL, _("_Attesa Pulsante"));
  gtk_widget_set_name (rb_attesa_pulsante, "rb_attesa_pulsante");
  gtk_widget_show (rb_attesa_pulsante);
  gtk_box_pack_start (GTK_BOX (vbox376), rb_attesa_pulsante, TRUE, TRUE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_attesa_pulsante), rb_attesa_pulsante_group);
  rb_attesa_pulsante_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_attesa_pulsante));

  hbox188 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox188, "hbox188");
  gtk_widget_show (hbox188);
  gtk_box_pack_start (GTK_BOX (vbox376), hbox188, TRUE, TRUE, 0);

  rb_pulsante_simulato = gtk_radio_button_new_with_mnemonic (NULL, _("Pulsante _Simulato"));
  gtk_widget_set_name (rb_pulsante_simulato, "rb_pulsante_simulato");
  gtk_widget_show (rb_pulsante_simulato);
  gtk_box_pack_start (GTK_BOX (hbox188), rb_pulsante_simulato, TRUE, TRUE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_pulsante_simulato), rb_attesa_pulsante_group);
  rb_attesa_pulsante_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_pulsante_simulato));

  hbox189 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox189, "hbox189");
  gtk_widget_show (hbox189);
  gtk_box_pack_start (GTK_BOX (hbox188), hbox189, TRUE, TRUE, 0);

  label1230b = gtk_label_new (_("Attesa (ms)"));
  gtk_widget_set_name (label1230b, "label1230b");
  gtk_widget_show (label1230b);
  gtk_box_pack_start (GTK_BOX (hbox189), label1230b, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label1230b), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label1230b), 0, 0.5);

  sb_delay_adj = gtk_adjustment_new (100, 100, 100000, 100, 100, 10);
  sb_delay = gtk_spin_button_new (GTK_ADJUSTMENT (sb_delay_adj), 1, 0);
  gtk_widget_set_name (sb_delay, "sb_delay");
  gtk_widget_show (sb_delay);
  gtk_box_pack_start (GTK_BOX (hbox189), sb_delay, TRUE, TRUE, 0);

  label1230 = gtk_label_new (_("Pressione pulsante"));
  gtk_widget_set_name (label1230, "label1230");
  gtk_widget_show (label1230);
  gtk_frame_set_label_widget (GTK_FRAME (frame538), label1230);

  frame539 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame539, "frame539");
  gtk_widget_show (frame539);
  gtk_box_pack_start (GTK_BOX (hbox186), frame539, TRUE, TRUE, 0);

  tb_ciclo_infinito = gtk_check_button_new_with_mnemonic (_("_Ciclo infifnito"));
  gtk_widget_set_name (tb_ciclo_infinito, "tb_ciclo_infinito");
  gtk_widget_show (tb_ciclo_infinito);
  gtk_container_add (GTK_CONTAINER (frame539), tb_ciclo_infinito);

  label1231 = gtk_label_new (_("Ciclo"));
  gtk_widget_set_name (label1231, "label1231");
  gtk_widget_show (label1231);
  gtk_frame_set_label_widget (GTK_FRAME (frame539), label1231);

  sw_list = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (sw_list, "sw_list");
  gtk_widget_show (sw_list);
  gtk_box_pack_start (GTK_BOX (vbox374), sw_list, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (sw_list, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (sw_list), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  frame540 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame540, "frame540");
  gtk_widget_show (frame540);
  gtk_box_pack_start (GTK_BOX (vbox371), frame540, TRUE, TRUE, 0);

  lb_msg = gtk_label_new ("");
  gtk_widget_set_name (lb_msg, "lb_msg");
  gtk_widget_show (lb_msg);
  gtk_container_add (GTK_CONTAINER (frame540), lb_msg);
  gtk_label_set_justify (GTK_LABEL (lb_msg), GTK_JUSTIFY_CENTER);

  hseparator11 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator11, "hseparator11");
  gtk_widget_show (hseparator11);
  gtk_box_pack_start (GTK_BOX (vbox371), hseparator11, FALSE, FALSE, 0);

  hbuttonbox9 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox9, "hbuttonbox9");
  gtk_widget_show (hbuttonbox9);
  gtk_box_pack_start (GTK_BOX (vbox371), hbuttonbox9, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox9), GTK_BUTTONBOX_SPREAD);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox9), 30);

  pb_start = gtk_button_new ();
  gtk_widget_set_name (pb_start, "pb_start");
  gtk_widget_show (pb_start);
  gtk_container_add (GTK_CONTAINER (hbuttonbox9), pb_start);
  GTK_WIDGET_SET_FLAGS (pb_start, GTK_CAN_DEFAULT);

  vbox372 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox372, "vbox372");
  gtk_widget_show (vbox372);
  gtk_container_add (GTK_CONTAINER (pb_start), vbox372);

  pixmap256 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (pixmap256, "pixmap256");
  gtk_widget_show (pixmap256);
  gtk_box_pack_start (GTK_BOX (vbox372), pixmap256, TRUE, TRUE, 0);

  label1226 = gtk_label_new_with_mnemonic (_("_Start"));
  gtk_widget_set_name (label1226, "label1226");
  gtk_widget_show (label1226);
  gtk_box_pack_start (GTK_BOX (vbox372), label1226, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1226), GTK_JUSTIFY_CENTER);

  pb_stop = gtk_button_new ();
  gtk_widget_set_name (pb_stop, "pb_stop");
  gtk_widget_show (pb_stop);
  gtk_container_add (GTK_CONTAINER (hbuttonbox9), pb_stop);
  GTK_WIDGET_SET_FLAGS (pb_stop, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (pb_stop, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  vbox373 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox373, "vbox373");
  gtk_widget_show (vbox373);
  gtk_container_add (GTK_CONTAINER (pb_stop), vbox373);

  pixmap257 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (pixmap257, "pixmap257");
  gtk_widget_show (pixmap257);
  gtk_box_pack_start (GTK_BOX (vbox373), pixmap257, TRUE, TRUE, 0);

  label1227 = gtk_label_new_with_mnemonic (_("S_top"));
  gtk_widget_set_name (label1227, "label1227");
  gtk_widget_show (label1227);
  gtk_box_pack_start (GTK_BOX (vbox373), label1227, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1227), GTK_JUSTIFY_CENTER);

  pb_reset = gtk_button_new ();
  gtk_widget_set_name (pb_reset, "pb_reset");
  gtk_widget_show (pb_reset);
  gtk_container_add (GTK_CONTAINER (hbuttonbox9), pb_reset);
  GTK_WIDGET_SET_FLAGS (pb_reset, GTK_CAN_DEFAULT);

  vbox377 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox377, "vbox377");
  gtk_widget_show (vbox377);
  gtk_container_add (GTK_CONTAINER (pb_reset), vbox377);

  pixmap258 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (pixmap258, "pixmap258");
  gtk_widget_show (pixmap258);
  gtk_box_pack_start (GTK_BOX (vbox377), pixmap258, TRUE, TRUE, 0);

  label1228b = gtk_label_new_with_mnemonic (_("_Reset"));
  gtk_widget_set_name (label1228b, "label1228b");
  gtk_widget_show (label1228b);
  gtk_box_pack_start (GTK_BOX (vbox377), label1228b, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1228b), GTK_JUSTIFY_CENTER);

  pb_cancel = gtk_button_new ();
  gtk_widget_set_name (pb_cancel, "pb_cancel");
  gtk_widget_show (pb_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox9), pb_cancel);
  GTK_WIDGET_SET_FLAGS (pb_cancel, GTK_CAN_DEFAULT);

  vbox378 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox378, "vbox378");
  gtk_widget_show (vbox378);
  gtk_container_add (GTK_CONTAINER (pb_cancel), vbox378);

  pixmap259 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (pixmap259, "pixmap259");
  gtk_widget_show (pixmap259);
  gtk_box_pack_start (GTK_BOX (vbox378), pixmap259, TRUE, TRUE, 0);

  label1229b = gtk_label_new_with_mnemonic (_("_Cancel"));
  gtk_widget_set_name (label1229b, "label1229b");
  gtk_widget_show (label1229b);
  gtk_box_pack_start (GTK_BOX (vbox378), label1229b, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1229b), GTK_JUSTIFY_CENTER);

  g_signal_connect_swapped ((gpointer) rb_singolo_settore, "toggled",
                            G_CALLBACK (on_dlg_test_rb_singolo_settore_toggled),
                            GTK_OBJECT (dlg_test));
  g_signal_connect_swapped ((gpointer) rb_pulsante_simulato, "toggled",
                            G_CALLBACK (on_dlg_test_rb_pulsante_simulato_toggled),
                            GTK_OBJECT (dlg_test));
  g_signal_connect_data ((gpointer) pb_start, "clicked",
                         G_CALLBACK (on_dlg_test_pb_start_clicked),
                         GTK_OBJECT (dlg_test),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_swapped ((gpointer) pb_stop, "clicked",
                            G_CALLBACK (on_dlg_test_pb_stop_clicked),
                            GTK_OBJECT (dlg_test));
  g_signal_connect_swapped ((gpointer) pb_reset, "clicked",
                            G_CALLBACK (on_dlg_test_pb_reset_clicked),
                            GTK_OBJECT (dlg_test));
  g_signal_connect_swapped ((gpointer) pb_cancel, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dlg_test));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlg_test, dlg_test, "dlg_test");
  GLADE_HOOKUP_OBJECT (dlg_test, vbox371, "vbox371");
  GLADE_HOOKUP_OBJECT (dlg_test, frame536, "frame536");
  GLADE_HOOKUP_OBJECT (dlg_test, vbox374, "vbox374");
  GLADE_HOOKUP_OBJECT (dlg_test, hbox187, "hbox187");
  GLADE_HOOKUP_OBJECT (dlg_test, frame537, "frame537");
  GLADE_HOOKUP_OBJECT (dlg_test, vbox375, "vbox375");
  GLADE_HOOKUP_OBJECT (dlg_test, rb_tutti_i_settori, "rb_tutti_i_settori");
  GLADE_HOOKUP_OBJECT (dlg_test, hbox184, "hbox184");
  GLADE_HOOKUP_OBJECT (dlg_test, rb_singolo_settore, "rb_singolo_settore");
  GLADE_HOOKUP_OBJECT (dlg_test, hbox185, "hbox185");
  GLADE_HOOKUP_OBJECT (dlg_test, lb_settore, "lb_settore");
  GLADE_HOOKUP_OBJECT (dlg_test, sb_settore, "sb_settore");
  GLADE_HOOKUP_OBJECT (dlg_test, label1228, "label1228");
  GLADE_HOOKUP_OBJECT (dlg_test, frame541, "frame541");
  GLADE_HOOKUP_OBJECT (dlg_test, vbox379, "vbox379");
  GLADE_HOOKUP_OBJECT (dlg_test, rb_priorita, "rb_priorita");
  GLADE_HOOKUP_OBJECT (dlg_test, rb_ubicazione, "rb_ubicazione");
  GLADE_HOOKUP_OBJECT (dlg_test, label1229, "label1229");
  GLADE_HOOKUP_OBJECT (dlg_test, hbox186, "hbox186");
  GLADE_HOOKUP_OBJECT (dlg_test, frame538, "frame538");
  GLADE_HOOKUP_OBJECT (dlg_test, vbox376, "vbox376");
  GLADE_HOOKUP_OBJECT (dlg_test, rb_attesa_pulsante, "rb_attesa_pulsante");
  GLADE_HOOKUP_OBJECT (dlg_test, hbox188, "hbox188");
  GLADE_HOOKUP_OBJECT (dlg_test, rb_pulsante_simulato, "rb_pulsante_simulato");
  GLADE_HOOKUP_OBJECT (dlg_test, hbox189, "hbox189");
  GLADE_HOOKUP_OBJECT (dlg_test, label1230b, "label1230b");
  GLADE_HOOKUP_OBJECT (dlg_test, sb_delay, "sb_delay");
  GLADE_HOOKUP_OBJECT (dlg_test, label1230, "label1230");
  GLADE_HOOKUP_OBJECT (dlg_test, frame539, "frame539");
  GLADE_HOOKUP_OBJECT (dlg_test, tb_ciclo_infinito, "tb_ciclo_infinito");
  GLADE_HOOKUP_OBJECT (dlg_test, label1231, "label1231");
  GLADE_HOOKUP_OBJECT (dlg_test, sw_list, "sw_list");
  GLADE_HOOKUP_OBJECT (dlg_test, frame540, "frame540");
  GLADE_HOOKUP_OBJECT (dlg_test, lb_msg, "lb_msg");
  GLADE_HOOKUP_OBJECT (dlg_test, hseparator11, "hseparator11");
  GLADE_HOOKUP_OBJECT (dlg_test, hbuttonbox9, "hbuttonbox9");
  GLADE_HOOKUP_OBJECT (dlg_test, pb_start, "pb_start");
  GLADE_HOOKUP_OBJECT (dlg_test, vbox372, "vbox372");
  GLADE_HOOKUP_OBJECT (dlg_test, pixmap256, "pixmap256");
  GLADE_HOOKUP_OBJECT (dlg_test, label1226, "label1226");
  GLADE_HOOKUP_OBJECT (dlg_test, pb_stop, "pb_stop");
  GLADE_HOOKUP_OBJECT (dlg_test, vbox373, "vbox373");
  GLADE_HOOKUP_OBJECT (dlg_test, pixmap257, "pixmap257");
  GLADE_HOOKUP_OBJECT (dlg_test, label1227, "label1227");
  GLADE_HOOKUP_OBJECT (dlg_test, pb_reset, "pb_reset");
  GLADE_HOOKUP_OBJECT (dlg_test, vbox377, "vbox377");
  GLADE_HOOKUP_OBJECT (dlg_test, pixmap258, "pixmap258");
  GLADE_HOOKUP_OBJECT (dlg_test, label1228b, "label1228b");
  GLADE_HOOKUP_OBJECT (dlg_test, pb_cancel, "pb_cancel");
  GLADE_HOOKUP_OBJECT (dlg_test, vbox378, "vbox378");
  GLADE_HOOKUP_OBJECT (dlg_test, pixmap259, "pixmap259");
  GLADE_HOOKUP_OBJECT (dlg_test, label1229b, "label1229b");

  gtk_window_add_accel_group (GTK_WINDOW (dlg_test), accel_group);

  return dlg_test;
}

static GnomeUIInfo archivio_menu_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Stampa"),
    N_("stampa la lista visualizzata a video"),
    (gpointer) on_pbm_print_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_S, (GdkModifierType) GDK_CONTROL_MASK, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_Uscita"),
    N_("Exit application"),
    (gpointer) on_pbm_exit_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_Q, (GdkModifierType) GDK_CONTROL_MASK, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo visualizza_menu_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Aggiorna"),
    N_("Aggiorna"),
    (gpointer) on_pbm_aggiorna_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_W, (GdkModifierType) GDK_CONTROL_MASK, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo help_menu_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_About"),
    NULL,
    (gpointer) on_pbm_about_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_F1, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Help"),
    NULL,
    (gpointer) on_pbm_help_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_H, (GdkModifierType) GDK_CONTROL_MASK, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mb_main_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_Archivi"),
    NULL,
    archivio_menu_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Visualizza"),
    NULL,
    visualizza_menu_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Help"),
    NULL,
    help_menu_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *bonobodock1;
  GtkWidget *vbox1;
  GtkWidget *hbox19;
  GtkWidget *frame148;
  GtkWidget *pixmap_cni;
  GtkWidget *toolbar1;
  gint tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *pb_test;
  GtkWidget *pb_print;
  GtkWidget *separatortoolitem1;
  GtkWidget *pb_config;
  GtkWidget *separatortoolitem2;
  GtkWidget *pb_exit;
  GtkWidget *frame149;
  GtkWidget *pixmap_customer;
  GtkWidget *vbox183;
  GtkWidget *vpaned_main;
  GtkWidget *sw_main;
  GtkWidget *hbox21;
  GtkWidget *sw_msgs;
  GtkWidget *txt_msgs;
  GtkWidget *ab_main;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  main_window = gnome_app_new ("Test", _("Test"));
  gtk_widget_set_name (main_window, "main_window");
  gtk_window_set_default_size (GTK_WINDOW (main_window), 900, 700);

  bonobodock1 = GNOME_APP (main_window)->dock;
  gtk_widget_set_name (bonobodock1, "bonobodock1");
  gtk_widget_show (bonobodock1);

  gnome_app_create_menus (GNOME_APP (main_window), mb_main_uiinfo);

  gtk_widget_set_name (mb_main_uiinfo[0].widget, "archivio_menu");

  gtk_widget_set_name (archivio_menu_menu_uiinfo[0].widget, "pbm_print");

  gtk_widget_set_name (archivio_menu_menu_uiinfo[1].widget, "separator1");

  gtk_widget_set_name (archivio_menu_menu_uiinfo[2].widget, "pbm_exit");

  gtk_widget_set_name (mb_main_uiinfo[1].widget, "visualizza_menu");

  gtk_widget_set_name (visualizza_menu_menu_uiinfo[0].widget, "aggiorna");

  gtk_widget_set_name (mb_main_uiinfo[2].widget, "help_menu");

  gtk_widget_set_name (help_menu_menu_uiinfo[0].widget, "pbm_about");

  gtk_widget_set_name (help_menu_menu_uiinfo[1].widget, "pbm_help");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gnome_app_set_contents (GNOME_APP (main_window), vbox1);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox19, "hbox19");
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox19, FALSE, FALSE, 0);

  frame148 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame148, "frame148");
  gtk_widget_show (frame148);
  gtk_box_pack_start (GTK_BOX (hbox19), frame148, FALSE, FALSE, 0);

  pixmap_cni = create_pixmap (main_window, "test/AEL-GLOSSY-small.png");
  gtk_widget_set_name (pixmap_cni, "pixmap_cni");
  gtk_widget_show (pixmap_cni);
  gtk_container_add (GTK_CONTAINER (frame148), pixmap_cni);
  gtk_misc_set_padding (GTK_MISC (pixmap_cni), 2, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (hbox19), toolbar1, TRUE, TRUE, 3);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  gtk_toolbar_set_show_arrow (GTK_TOOLBAR (toolbar1), FALSE);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  pb_test = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Test"));
  gtk_widget_set_name (pb_test, "pb_test");
  gtk_widget_show (pb_test);
  gtk_container_add (GTK_CONTAINER (toolbar1), pb_test);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (pb_test), tooltips, _("Test"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-print", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  pb_print = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Stampa"));
  gtk_widget_set_name (pb_print, "pb_print");
  gtk_widget_show (pb_print);
  gtk_container_add (GTK_CONTAINER (toolbar1), pb_print);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (pb_print), tooltips, _("Stampa"), NULL);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem1, "separatortoolitem1");
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem1);

  tmp_image = gtk_image_new_from_stock ("gtk-preferences", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  pb_config = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Setup"));
  gtk_widget_set_name (pb_config, "pb_config");
  gtk_widget_show (pb_config);
  gtk_container_add (GTK_CONTAINER (toolbar1), pb_config);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (pb_config), tooltips, _("Modifica parametri di funzionamento"), NULL);

  separatortoolitem2 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem2, "separatortoolitem2");
  gtk_widget_show (separatortoolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem2);

  pb_exit = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-quit");
  gtk_widget_set_name (pb_exit, "pb_exit");
  gtk_widget_show (pb_exit);
  gtk_container_add (GTK_CONTAINER (toolbar1), pb_exit);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (pb_exit), tooltips, _("Uscita dall'applicazione"), NULL);

  frame149 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame149, "frame149");
  gtk_widget_show (frame149);
  gtk_box_pack_start (GTK_BOX (hbox19), frame149, FALSE, FALSE, 0);

  pixmap_customer = create_pixmap (main_window, "test/logo_azienda.png");
  gtk_widget_set_name (pixmap_customer, "pixmap_customer");
  gtk_widget_show (pixmap_customer);
  gtk_container_add (GTK_CONTAINER (frame149), pixmap_customer);
  gtk_misc_set_padding (GTK_MISC (pixmap_customer), 10, 0);

  vbox183 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox183, "vbox183");
  gtk_widget_show (vbox183);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox183, TRUE, TRUE, 2);

  vpaned_main = gtk_vpaned_new ();
  gtk_widget_set_name (vpaned_main, "vpaned_main");
  gtk_widget_show (vpaned_main);
  gtk_box_pack_start (GTK_BOX (vbox183), vpaned_main, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (vpaned_main, GTK_CAN_FOCUS);
  gtk_paned_set_position (GTK_PANED (vpaned_main), 400);

  sw_main = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (sw_main, "sw_main");
  gtk_widget_show (sw_main);
  gtk_paned_pack1 (GTK_PANED (vpaned_main), sw_main, FALSE, TRUE);
  GTK_WIDGET_UNSET_FLAGS (sw_main, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (sw_main), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox21, "hbox21");
  gtk_widget_show (hbox21);
  gtk_paned_pack2 (GTK_PANED (vpaned_main), hbox21, TRUE, TRUE);

  sw_msgs = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (sw_msgs, "sw_msgs");
  gtk_widget_show (sw_msgs);
  gtk_box_pack_start (GTK_BOX (hbox21), sw_msgs, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (sw_msgs), 5);
  GTK_WIDGET_UNSET_FLAGS (sw_msgs, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (sw_msgs), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (sw_msgs), GTK_SHADOW_IN);

  txt_msgs = gtk_text_view_new ();
  gtk_widget_set_name (txt_msgs, "txt_msgs");
  gtk_widget_show (txt_msgs);
  gtk_container_add (GTK_CONTAINER (sw_msgs), txt_msgs);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (txt_msgs), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (txt_msgs), GTK_WRAP_WORD);

  ab_main = gnome_appbar_new (TRUE, TRUE, GNOME_PREFERENCES_NEVER);
  gtk_widget_set_name (ab_main, "ab_main");
  gtk_widget_show (ab_main);
  gnome_app_set_statusbar (GNOME_APP (main_window), ab_main);

  gnome_app_install_menu_hints (GNOME_APP (main_window), mb_main_uiinfo);
  g_signal_connect ((gpointer) pb_test, "clicked",
                    G_CALLBACK (on_main_pb_test_clicked),
                    NULL);
  g_signal_connect ((gpointer) pb_print, "clicked",
                    G_CALLBACK (on_main_pb_print_clicked),
                    NULL);
  g_signal_connect ((gpointer) pb_config, "clicked",
                    G_CALLBACK (on_main_pb_config_clicked),
                    NULL);
  g_signal_connect ((gpointer) pb_exit, "clicked",
                    G_CALLBACK (on_main_pb_exit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, bonobodock1, "bonobodock1");
  GLADE_HOOKUP_OBJECT (main_window, mb_main_uiinfo[0].widget, "archivio_menu");
  GLADE_HOOKUP_OBJECT (main_window, archivio_menu_menu_uiinfo[0].widget, "pbm_print");
  GLADE_HOOKUP_OBJECT (main_window, archivio_menu_menu_uiinfo[1].widget, "separator1");
  GLADE_HOOKUP_OBJECT (main_window, archivio_menu_menu_uiinfo[2].widget, "pbm_exit");
  GLADE_HOOKUP_OBJECT (main_window, mb_main_uiinfo[1].widget, "visualizza_menu");
  GLADE_HOOKUP_OBJECT (main_window, visualizza_menu_menu_uiinfo[0].widget, "aggiorna");
  GLADE_HOOKUP_OBJECT (main_window, mb_main_uiinfo[2].widget, "help_menu");
  GLADE_HOOKUP_OBJECT (main_window, help_menu_menu_uiinfo[0].widget, "pbm_about");
  GLADE_HOOKUP_OBJECT (main_window, help_menu_menu_uiinfo[1].widget, "pbm_help");
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (main_window, frame148, "frame148");
  GLADE_HOOKUP_OBJECT (main_window, pixmap_cni, "pixmap_cni");
  GLADE_HOOKUP_OBJECT (main_window, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (main_window, pb_test, "pb_test");
  GLADE_HOOKUP_OBJECT (main_window, pb_print, "pb_print");
  GLADE_HOOKUP_OBJECT (main_window, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (main_window, pb_config, "pb_config");
  GLADE_HOOKUP_OBJECT (main_window, separatortoolitem2, "separatortoolitem2");
  GLADE_HOOKUP_OBJECT (main_window, pb_exit, "pb_exit");
  GLADE_HOOKUP_OBJECT (main_window, frame149, "frame149");
  GLADE_HOOKUP_OBJECT (main_window, pixmap_customer, "pixmap_customer");
  GLADE_HOOKUP_OBJECT (main_window, vbox183, "vbox183");
  GLADE_HOOKUP_OBJECT (main_window, vpaned_main, "vpaned_main");
  GLADE_HOOKUP_OBJECT (main_window, sw_main, "sw_main");
  GLADE_HOOKUP_OBJECT (main_window, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (main_window, sw_msgs, "sw_msgs");
  GLADE_HOOKUP_OBJECT (main_window, txt_msgs, "txt_msgs");
  GLADE_HOOKUP_OBJECT (main_window, ab_main, "ab_main");
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, tooltips, "tooltips");

  return main_window;
}

