# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = carichi

BASE_DIRECTORY = ..

TARGET_SRCS = \
	main.c \
	mainapp.c \
	mainwin.c \
	mainvar.c \
	mainfun.c \
	mainproc.c \
	conteggia_prodotto.c \
	differenza_inventariale.c \
	edit_bancale.c \
	edit_distinta.c \
	edit_prodotto.c \
	import_spedizioni.c \
	import_catalogo.c \
	ingresso_merce.c \
	insert_distinta.c \
	insert_prodotto.c \
	insert_quantity.c \
	insert_udc.c \
	spedizione_merce.c \
	ep-popover.c \
	resources.c

TARGET_INCLUDES = \
	conteggia_prodotto.h \
	differenza_inventariale.h \
	edit_bancale.h \
	edit_distinta.h \
	edit_prodotto.h \
	import_catalogo.h \
	import_spedizioni.h \
	ingresso_merce.h \
	insert_distinta.h \
	insert_prodotto.h \
	insert_quantity.h \
	insert_udc.h \
	mainapp.h \
	mainext.h \
	mainfun.h \
	mainstruct.h \
	mainwin.h \
	spedizione_merce.h


include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
