/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_dlg_about (void);
GtkWidget* create_dlg_exit (void);
GtkWidget* create_dlg_message (void);
GtkWidget* create_dlg_config (void);
GtkWidget* create_dlg_edit_ordine (void);
GtkWidget* create_dlg_edit_collo (void);
GtkWidget* create_dlg_opeset (void);
GtkWidget* create_dlg_imballi (void);
GtkWidget* create_dlg_ubicazioni (void);
GtkWidget* create_dlg_catalogo (void);
GtkWidget* create_dlg_operatori (void);
GtkWidget* create_dlg_search (void);
GtkWidget* create_dlg_edit (void);
GtkWidget* create_window1 (void);
GtkWidget* create_dlg_cedola (void);
GtkWidget* create_dlg_select (void);
GtkWidget* create_dlg_expand (void);
GtkWidget* create_main_window (void);
