# ---------------------------------------------------------
# target makefile
# ---------------------------------------------------------
#
TOPTARGETS := all clean install release 

TARGET_NAME = writeshm

BASE_DIRECTORY = ..

TARGET_SRCS = writeshm.c

TARGET_INCLUDES = 

include $(BASE_DIRECTORY)/common/common.mak

.PHONY: $(TOPTARGETS)
