/*
* printlabel.h
* 
* Progetto Mondadori Picking
*
* Autore : Roberto Mantovani
*
* Copyright A&L srl 2003-2021
*/
#if 0
#ifndef BOOL_TYPE_DEFINED
typedef unsigned int BOOL;
#define FALSE	0
#define TRUE 	1
#define BOOL_TYPE_DEFINED
#endif
#endif

#define LEFT	0
#define RIGHT	1

#ifndef MIN_MAX_DEFINED
#define max(a,b)	((a)>=(b)?(a):(b))
#define min(a,b)	((a)<=(b)?(a):(b))
#endif

enum RACFIELD {
	F_STOCCAGGIO,
	F_QUANTITA,
	F_TITOLO,
	F_AUTORE,
	F_CODPRO,
	F_PREZZO,
	F_SPEDIZ,
	F_PACCO,
	F_DATA,
	F_PAG,
	F_AREA,
	F_CODDEST,
	F_TOTPACCHI,
	F_RIGHE,
	F_VOLUMI,
	F_TOTRIGHE,
	F_TOTVOLUMI,
	F_NOTE,
	F_FORIGHE,
	F_FOVOLUMI,
	F_ETISPEDIZ,
	F_ETINUMPACCO,
	F_ETIR1C1,
	F_ETIR1C2,
	F_ETIR1C3,
	F_ETIR1C4,
	F_ETIR2,
	F_ETIR3,
	F_ETIR4,
	F_ETIR5C1,
	F_ETIR5C2,
	F_ETIR5C3,
	F_ETIR6,
	F_ETIPESO,
	F_ETIINDICAZ,
	F_ETIDATABAM,
	F_ETIDATASTAMPA,
	F_ETIFORCOLLO,
	F_ETICODSOVR,
	F_ETIBARCODE,
	F_DSLINEA,

	NUM_FIELD_RAC
};

enum XABFIELD{
	F_DESTINATARIO0,
	F_DESTINATARIO1,
	F_DESTINATARIO2,
	F_DESTINATARIO3,
	F_DESTINATARIO4,
	F_DESTINATARIO5,
	F_DESTINATARIO6,
	F_DESTINATARIO7,
	F_DESTINATARIO8,
	F_DESTINATARIO9,
	F_NUMEROINALTO,
	F_DATAXAB,
	F_DOCUMENTOINTERNO0,
	F_DOCUMENTOINTERNO1,
	F_DOCUMENTOINTERNO2,
	F_NUMEROINBASSO,
	F_SPEDIZIONE,
	F_CAUSALE,
	F_CONTENUTO,
	F_PORTO,
	F_DESTINAZIONE0,
	F_DESTINAZIONE1,
	F_DESTINAZIONE2,
	F_DESTINAZIONE3,
	F_DESTINAZIONE4,
	F_DESTINAZIONE5,
	F_DESTINAZIONE6,
	F_DATAORACONSEGNA,
	F_FIRMADESTINATARIO,
	F_ASSEGNO,
	F_ASPETTOBENI,
	F_CODICE,
	F_AUTOREXAB,
	F_TITOLOXAB,
	F_QUANTITACIFRE,
	F_QUANTITALETTERE,
	F_PREZZOXAB,
	F_IVA,
	F_VETTORI0,
	F_VETTORI1,
	F_VETTORI2,
	F_VETTORI3,
	F_VETTORI4,
	F_VETTORI5,
	F_QUANTITAXAB,
	F_PESO,
	F_NUMCOLLI,
	F_ANNOTAZIONI,
	F_VARIAZDEST,
	F_FINEBOLLA,

	NUM_FIELD_XAB
};

enum DISFIELD{
	F_NUMERODISTINTA,
	F_NUMEROPAGINA,
	F_MAGAZZINO,
	F_TPSPED,
	F_DESCRIZIONETPSPED,
	F_TPSPEDLINSCASSC,
	F_DATADOCUMENTO,
	F_DATASTAMPA,
	F_PROGRSPEDIZ,
	F_SPEDIZIONEDIS,
	F_DESTINATARIO,
	F_DESTINAZIONE,
	F_DATABAM,
	F_NUMEROPACCHI,
	F_PESODISTINTA,
	F_NUMEROPEZZI,
	F_TASSASPEDIZ,
	F_TOTALESPEDIZ,
	F_TOTALEPACCHI,
	F_TOTALEPESO,
	F_TOTALEVOLUMI,
	F_TOTALETASSASPEDIZ,
	F_DSVET1,
	F_INVET1,
	F_LOVET1,
	F_DSVET2,
	F_INVET2,
	F_LOVET2,
	F_DATARIITIRO,
	F_ORARITIRO,

	NUM_FIELD_DIS
};

enum ERRDISTINTA{
	ERR_NOSPED=1,
	ERR_INITPRINT,
	ERR_STMPRSTMP,
	ERR_WRONGSTATE,
	ERR_NORICORD
};

enum STAMPADISTINTA{
	INIZIALIZZAZIONE,
	NUOVASTAMPA,
	RISTAMPA
};

#define MAX_RAC_LINES        256
#define MAX_RAC_LINE_LEN     132
#define MAX_RIGHE_XAB  		   72
#define MAX_COLONNE_XAB  	   80
#define MAX_RIGHE_XAB_A4	   99
#define MAX_COLONNE_XAB_A4   95
#define MAX_RIGHE_DIS  		   72
#define MAX_COLONNE_DIS  	   80
#define MAX_RIGHE_DC	 		   18
#define MAX_COLONNE_DC       83
